### ISSUE TITLE
Message TODO

### ISSUE THREAD

**Issue by Rheydskey** [Fydia/fydia#150]
- [x] Edit Message (Websocket Event)
- [x] Delete Message (Websocket Event)
- [ ] Direct Message
   - [x] Creation of DM
   - [ ] Update name of a DM (only groups)
   - [ ] Delete a DM
      - [ ] All Message into
